### ISSUE TITLE
v0.9.0: farmer: Error getting harvesters: strconv.Atoi: parsing \"null\": invalid syntax\n

### ISSUE THREAD

**Issue by stefan-lange** [Chia-Network/chia-exporter#108]
environment:
- chia-exporter: 0.9.0
- chia: 1.8.2.giga14
- farmer and harvester in separate containers/pods

logs:
time="2023-08-25T14:02:15+02:00" level=debug msg="origin: chia_farmer command: get_connections destination: go-chia-rpc data: {\"connections\": [{\"bytes_read\": 418, \"bytes_written\": 64, \"creation_time\": 1692964882.2185738, \"last_message_time\": 1692964926.6347077, \"local_port\": 8447, \"node_id\": \"0x@ABC@\", \"peer_host\": \"127.0.0.1\", \"peer_port\": 8444, \"peer_server_port\": 8444, \"type\": 1}, {\"bytes_read\": 64, \"bytes_written\": 303, \"creation_time\": 1692964935.7108257, \"last_message_time\": 1692964935.7117414, \"local_port\": 8447, \"node_id\": \"0x@XYZ@\", \"peer_host\": \"10.42.1.72\", \"peer_port\": 47078, \"peer_server_port\": 8448, \"type\": 2}], \"success\": true}\n"
time="2023-08-25T14:02:15+02:00" level=error msg="farmer: Error getting harvesters: strconv.Atoi: parsing \"null\": invalid syntax\n"

also many messages in the log:
time="2023-08-25T14:03:46+02:00" level=debug msg="Missing node ID to host mapping or plot count doesn't match. Refreshing harvester info. New Plot Count: 7965 | Previous Plot Count: 0\n

The exporter exports data, but the error is "annoying".

Could be a compatibility issue with chia <=1.8.2? I haven't found a note in the release. Chia-exporter 0.8.0 works without problems.

If it's gigahorse related, the ticket can be closed.

**Comment by cmmarslender** [comment]
There is definitely new data that is only available in 2.0.0 (being able to get harvester info centrally from the farmer vs having to install this on all the harvesters as well). The error sounds like its because of missing fields in that harvester info request that aren't present in 1.8.2. I can take a look and see if I can make it a bit less annoying in the logs

**Comment by cmmarslender** [comment]
Im going to close this issue out since its probably not going to get priority, primarily because using 2.1.0+ is required for hard fork compatibility. Gigahorse also has newer versions out as well now that should make this issue no longer an issue.
