### ISSUE TITLE
chia_harvester_plot_count not updating

### ISSUE THREAD

**Issue by Jahorse** [Chia-Network/chia-exporter#118]
I'm using chia-exporter v0.10.0 running as a service on Ubuntu 22.04.3 with Chia v2.1.1.

I have noticed that if I delete all of a certain plot type, the `chia_harvester_plot_count` will continue to report 1 plot of that type until I restart chia-exporter. For example, I finished converting all my c0 plots to c7 plots and continued to see `chia_harvester_plot_count{compression="0",size="32",type="pool"} 1` in the metrics. I have been able to reproduce this on a different machine as well.

In my cases, it has always been going from 1 to 0, but I think it would happen for any value going to 0. I'm not very familiar with go and didn't look too closely, but it appears that this function is iterating over the list of plots the harvester detects and collecting the file size and count for all the k and c combinations that are present, skipping over anything that isn't present. 

I think to fix this, you'd either need to loop over `s.plotFileSize` and `s.plotCount` in `ProcessGetPlots` to remove entries that don't appear in the return values from `PlotSizeCountHelper`, or if you can maintain state between runs of `PlotSizeCountHelper` it could track the plot types that appear each run to compare against in the next run and return the list of plot types that were removed.

https://github.com/Chia-Network/chia-exporter/blob/734c039e3e8b5f68a5e3a85333bbf6695c825997/internal/metrics/harvester.go#L179

**Comment by cmmarslender** [comment]
Sorry about that. This was fixed when fetching all plot data from the farmer, but was not fixed for the case when chia exporter is installed on all harvesters. PR open and this should be fixed in the next release.
