### ISSUE TITLE
error_msg in chia_exporter

### ISSUE THREAD

**Issue by fermunt** [Chia-Network/chia-exporter#128]
Environment:
- OS: Windows 10
- Chia: 2.1.3
- chia_exporter: 0.11.0

Description: After transferring the database file, I get errors in chia_exporter:
```
time="2023-12-21T12:08:21+03:00" level=error msg="CreateFile C:\\Users\\User\\.chia\\mainnet\\F:\\chia\\db\\blockchain_v2_mainnet.sqlite: The filename, directory name, or volume label syntax is incorrect.\n"
time="2023-12-21T12:08:21+03:00" level=error msg="CreateFile C:\\Users\\User\\.chia\\mainnet\\F:\\chia\\db\\blockchain_v2_mainnet.sqlite-wal: The filename, directory name, or volume label syntax is incorrect.\n"
time="2023-12-21T12:08:21+03:00" level=error msg="CreateFile C:\\Users\\User\\.chia\\mainnet\\F:\\chia\\db\\blockchain_v2_mainnet.sqlite-shm: The filename, directory name, or volume label syntax is incorrect.\n"
```

Original settings file config.yaml:
```
full_node:
  database_path: db/blockchain_v2_CHALLENGE.sqlite
```

Modified settings file config.yaml:
```
full_node:
  database_path: F:/chia/db/blockchain_v2_CHALLENGE.sqlite
```

**Comment by cmmarslender** [comment]
Thanks for the report. I have a thought on why this may be happening and will take a look.
In the meantime, the error shouldn't be preventing the rest of the metrics from scraping correctly, so you should be ok to keep using exporter without worrying about something breaking.

**Comment by cmmarslender** [comment]
0.11.1 should solve this issue.
