### ISSUE TITLE
MySQL error 

### ISSUE THREAD

**Issue by rkroelin** [Chia-Network/chia-exporter#162]
I'm seeing this on a couple of my harvesters. I suspect it is related to how I set permissions up on the deployment of chia or chia-exporter but I can't for the life of me figure it out.

Any ideas?  Thanks!!

May 19 00:06:21 DrHarvester01 systemd[1]: Started Chia Exporter Service.
May 19 00:06:21 DrHarvester01 chia-exporter[2173879]: time="2024-05-19T00:06:21Z" level=error msg="Error ensuring tables exist in MySQL. Will not process or store any MySQL only me>May 19 00:06:21 DrHarvester01 chia-exporter[2173879]: time="2024-05-19T00:06:21Z" level=info msg="Starting metrics server on port 9914"
May 19 00:06:21 DrHarvester01 chia-exporter[2173879]: time="2024-05-19T00:06:21Z" level=error msg="error ensuring connection: dial tcp [::1]:55400: connect: connection refused"
May 19 00:06:26 DrHarvester01 chia-exporter[2173879]: time="2024-05-19T00:06:26Z" level=error msg="error ensuring connection: dial tcp [::1]:55400: connect: connection refused"

**Comment by rkroelin** [comment]
Relevant info maybe.  I've deployed my ca dir on these remote harvesters using 0600.  The systemd service fails unless I chown the directory with my user but then I run into the above error.

**Comment by cmmarslender** [comment]
MySQL is a very new and optional component of chia-exporter. Its currently only useful if you are running a network crawler along with the maxmind ASN database, and want to see the counts of peers per ASN. 

Log level of that should likely be warning instead of error

**Comment by rkroelin** [comment]
Ahh okay.  Thanks. I guess my issues running it on these two machines are unrelated to this error.

**Comment by cmmarslender** [comment]
> Ahh okay. Thanks. I guess my issues running it on these two machines are unrelated to this error.

Looking at the other parts of the log, its having an issue connecting to the daemon (55400). Are you trying to run chia exporter on a separate machine from chia? Its designed to run on the same machine next to chia
