### ISSUE TITLE
Issues with DrPlotter Harvester data?

### ISSUE THREAD

**Issue by rkroelin** [Chia-Network/chia-exporter#164]
Chia-exporter seems to be struggling with the data coming from DrPlotter harvesters.  DrPlotter v1.03.

May 21 18:09:33 DrChiaNode chia-exporter[6075]: time="2024-05-21T18:09:33Z" level=error msg="farmer: Error getting harvesters: strconv.Atoi: parsing \"null\": invalid syntax\n"

It seems to start and stop somewhat sporadically when multiple harvesters are present.

**Comment by cmmarslender** [comment]
> Chia-exporter seems to be struggling with the data coming from DrPlotter harvesters. DrPlotter v1.03.
> 
> May 21 18:09:33 DrChiaNode chia-exporter[6075]: time="2024-05-21T18:09:33Z" level=error msg="farmer: Error getting harvesters: strconv.Atoi: parsing "null": invalid syntax\n"
> 
> It seems to start and stop somewhat sporadically when multiple harvesters are present.

Can you run chia-exporter in DEBUG log mode and provide some additional logging output? Would be useful to see the full json payload that comes over that its having a hard time processing. Depending on the structure of the data, it may not be compatible with the chia-blockchain harvester format, but hard to say without more info.

Can DM me in keybase at `cmmarslender` if you want to keep the more detailed harvester logs out of a github issue

**Comment by rkroelin** [comment]
Sure, can do.  

If it matters the harvesters are running drchia in a docker container.  I'm struggling there with chia-exporter as well. Running the exporter service as root with the home and working directories mapped I still get the following: 

May 21 18:44:18  chia-exporter[329835]: time="2024-05-21T18:44:18Z" level=error msg="error ensuring connection: dial tcp [::1]:55400: connect: connection refused"

**Comment by cmmarslender** [comment]
The issue with getting harvester data via the farmer should be resolved in https://github.com/Chia-Network/chia-exporter/releases/tag/0.14.1

Running chia-exporter on the dr plotter harvester (without chia/chia daemon) is not supported, so I'd just rely on getting that data from farmer, and not installing chia-exporter with those harvesters
