### ISSUE TITLE
FR: Full Node Version

### ISSUE THREAD

**Issue by Ac3sRwild** [Chia-Network/chia-exporter#177]
If possible it would be nice to expose the full node version string.

**Comment by cmmarslender** [comment]
I think this is a good suggestion. Unfortunately, there isn't currently an RPC endpoint that exposes the version in chia-blockchain. I'll see if I can get one added and then we can look into doing this

**Comment by cmmarslender** [comment]
https://github.com/Chia-Network/chia-blockchain/pull/18366

**Comment by cmmarslender** [comment]
Everything is in place for this upstream, but it wont be supported until the next release of Chia-Blockchain, so going to hold off implementing it until then and then we can release a new version of exporter

**Comment by Ac3sRwild** [comment]
After a recent update it seems the `chia_full_node_version` metric is no longer available

**Comment by cmmarslender** [comment]
> After a recent update it seems the `chia_full_node_version` metric is no longer available

I assume you are on the latest version of chia-exporter? What version of chia are you running?

**Comment by Ac3sRwild** [comment]
I'm on the latest exporter version 16.2. And yes i just confirmed you are correct. There was a container update for the full node and that's when i lost the version metric. Restarting the exporter container restored the version metric
