### ISSUE TITLE
How to run on Windows. Neither an Installer nor a exe ?

### ISSUE THREAD

**Issue by mazm786** [Chia-Network/chia-exporter#21]
As Described in wiki:
`Chia exporter expects to be run on the same machine as the chia blockchain installation`

Chia blockchain latest version 1.3.3 has been installed but there is no Chia-Exporter. While File downloaded from this path
[https://github.com/Chia-Network/chia-exporter/releases/tag/0.0.5](url) is Neither an Installer nor a exe. **Then how to run chia-exporter Service on Windows 10 ?**

**Comment by cmmarslender** [comment]
The file is actually an executable, it is just missing the `.exe` extension for some reason. I'll get that fixed for the next release, but in the meantime, if you add `.exe` to the file, you should be able to run it like `chia-exporter.exe serve` from powershell or command prompt

**Comment by cmmarslender** [comment]
Fixed in https://github.com/Chia-Network/chia-exporter/releases/tag/0.0.6

**Comment by mazm786** [comment]
> Fixed in https://github.com/Chia-Network/chia-exporter/releases/tag/0.0.6

Thank you for Quick Response and Solution.
