### ISSUE TITLE
On Dashboard, Screen is stuck at https://dashboard.chia.net/login

### ISSUE THREAD

**Issue by mazm786** [Chia-Network/chia-exporter#24]
On Dashboard, Screen is stuck at https://dashboard.chia.net/login
**How to see Chia Exporter Data to this Chia_Dashboard ?** Any help please

![image](https://user-images.githubusercontent.com/68580069/162690374-9708ab94-820f-431d-a5a6-be0e78f3e6c7.png)

**Comment by cmmarslender** [comment]
Public dashboards have login, etc disabled. You can view the dashboard anonymously. For example: https://dashboard.chia.net/d/CL1X4UWnk/blockchain-state?orgId=1

**Comment by mazm786** [comment]
> Public dashboards have login, etc disabled. You can view the dashboard anonymously. For example: https://dashboard.chia.net/d/CL1X4UWnk/blockchain-state?orgId=1

Please guide.
I want to view my own system's status on chia-dashboard, What steps should I follow ? As login and etc are disabled on public dashboard. @cmmarslender @bramcohen @justinengland @Starttoaster
