### ISSUE TITLE
Feature request: harvester metrics / support multiple harvesters per ip

### ISSUE THREAD

**Issue by stefan-lange** [Chia-Network/chia-exporter#34]
Do the harvester metrics support multiple harvesters per ip? Currently this is an issue with chia-monitor (https://github.com/philippnormann/chia-monitor). It is not enough to use the ip as key, we need ip + nodeId (?) or something like that.

example `chia farm summary`
```
Farming status: Farming
Remote Harvesters for IP: 10.0.12.13
   165 plots of size: 16.331 TiB
   3120 plots of size: 308.795 TiB
Remote Harvester for IP: 10.0.0.12
   494 plots of size: 48.892 TiB
```

My goal is to re-create the beautiful dashboard made by Philipp from chia-monitor (https://github.com/philippnormann/chia-monitor/blob/main/.readme/grafana.png) with the data from the chia-exporter.

The cpu load of the chia-exporter is really low compared to chia-monitor although the chia-monitor has more features (today ;) ). Thank you for your work Chris.

**Comment by cmmarslender** [comment]
Each exporter will only talk to one chia daemon (and therefore only one harvester). If you have multiple harvesters on the same machine/IP, then they are presumably running multiple instances of chia-exporter on different ports with the `--metrics-port` flag?

Assuming that is true, you could set up a prometheus configuration like this:

```scrape_configs:
  - job_name: chia-exporter
    static_configs:
      - targets: ['1.2.3.4:9914']
        labels:
          application: 'chia-blockchain'
          network: 'mainnet'
          node_id: 'some-useful-node-id'
      - targets: ['1.2.3.4:9915']
        labels:
          application: 'chia-blockchain'
          network: 'mainnet'
          node_id: 'some-other-node-id'
```

`node_id` being the differentiator between the two different configs (application/network are optional, but just something I usually use)

Does that work, or did you have another solution in mind?

**Comment by stefan-lange** [comment]
My chia-farm is a complete 'infrastructure as code' docker swarm setup on different nodes and in the future in different locations. One-click deployment for lazy devs like me ;)
Chia-monitor has one advantage. It collects all information from all harvesters and there is only one scraping config needed. I don't know the internals, but I think the farmer seems to know also harvester data.

I'll play with your suggestion as soon as the next official chia version is out.

**Comment by cmmarslender** [comment]
I'll also try and set up a remote harvester and test where the events flow. If the metrics events end up at the remote farmer, then I can probably make this work with a single exporter, but I'm not sure if they do.

**Comment by cmmarslender** [comment]
Yeah I figured RPC calls was what was going on. As much as possible, I'm trying to architect this with no proactive RPC calls to anything. I'd rather listen to events that are being generated by Chia anyways, to not create additional load. This tool does make a few RPC calls, but even for those, its either because chia-exporter just started, or else its in response to another event, and I know for sure at that point that there would be new/changed data at the RPC, so its worth making the call.

**Comment by stefan-lange** [comment]
I think your approach is nice and a step in the right direction. Phillip did a great job back then too.

chia-exporters' cpu usage is really nice in comparison

```
chia	6936	6524	1	Jun01	?	00:21:46	.venv/bin/python -m monitor
chia	30285	6524	0	Jun01	?	00:00:23	/usr/local/bin/chia-exporter --metrics-port 9914 serve
```
