### ISSUE TITLE
FR: Allow overriding HTTP / RPC client target Host, enables Docker bridged networking

### ISSUE THREAD

**Issue by Artanicus** [Chia-Network/chia-exporter#49]
The go-chia-libs source seems to indicate the library supports overriding the default client host of localhost via client options: https://github.com/Chia-Network/go-chia-libs/blob/ceada8b288422263b24e855d6604b7504e43df51/pkg/httpclient/httpclient.go#L60

.. However chia-exporter does not provide a flag nor set any client options to provide said overrides. If that option existed it would allow a traditional Docker deployment of running the exporter as a sidecar with bridged networking and providing the address of the Chia container to the exporter. As it currently stands, using host networking on both containers is the only option to allow `localhost` to point to the right service.

**Comment by cmmarslender** [comment]
I need to actually go back and double check that we still support that. An early iteration definitely did support this, and then some of the client options got weird with the addition of the websocket support. I think hostname is something that should work in both cases though, so if its currently pulled out, it can likely get added back in as something to support.
