### ISSUE TITLE
chia_full_node_connection_count{node_type="harvester"} = 0, harvesters still connected

### ISSUE THREAD

**Issue by Artanicus** [Chia-Network/chia-exporter#65]
Everything is running fine and dandy and from the full_node:
```
# chia version
1.6.2
# chia farm summary
Farming status: Farming
<clip>
Local Harvester
   0 plots of size: 0.000 MiB
Remote Harvester for IP: 10.0.10.2
   XXX plots of size: Y TiB
Remote Harvester for IP: 10.0.10.3
   XXX plots of size: Y TiB
Plot count for all harvesters: XXXX
```

But from the metrics of that same node we get: `chia_full_node_connection_count{node_type="harvester"} = 0` whereas I'd have expected to see either 2 or 3, depending if the "Local Harvester" actually gets counted even though it's not running on that node.

`{node_type="farmer"}` has a value of 1. I mention this because the `chia peer -c` logic seems to be a bit different than the metrics. 

Again looking from the node running full_node & farmer:
```
# chia peer -c harvester
Connections:
Type      IP                                      Ports       NodeID      Last Connect      MiB Up|Dwn
FARMER    127.0.0.1                                8447/8447  xxx... Jan 15 18:03:44      0.0|0.0    
# chia peer -c farmer
Connections:
Type      IP                                      Ports       NodeID      Last Connect      MiB Up|Dwn
HARVESTER 10.0.10.2                               59032/8448  xxx... Jan 15 18:04:08      0.0|0.1    
HARVESTER 10.0.10.3                               38754/8448  xxx... Jan 15 18:04:08      0.0|0.3    
HARVESTER 127.0.0.1                               44468/8448  xxx... Jan 15 18:04:08      0.0|0.0    
FULL_NODE 127.0.0.1                                8444/8444  xxx... Jan 15 18:04:08      0.0|0.0    
                                                  -Height: No Info    -Hash: No Info    -Trusted: True
```

How can I troubleshoot deeper? Or is there a flaw in the logic for the metric?

**Comment by cmmarslender** [comment]
Im thinking through whats going on here, and I believe we're only showing full node peers in the metrics, not peers to the other services. If thats the case, what you are seeing makes sense, since the harvester connects to the farmer, not the full node. We can probably update this to show peers for the different services as well, but I'll need to look into it.

**Comment by cmmarslender** [comment]
This is currently in main, and will be included in the next release

**Comment by Artanicus** [comment]
Thanks for the quick turnaround! I'm now getting:
`chia_farmer_connection_count{node_type="harvester"} 3` as expected.
