### ISSUE TITLE
Issue with CHIA_ROOT

### ISSUE THREAD

**Issue by BubbleTrouble14** [Chia-Network/chia-exporter#79]
When running chia-exporter server it starts with no problem. But when trying to run it as a background service that also restarts on startup it doesnt check for the CHIA_ROOT path. Using this script from storage JM: https://gist.github.com/jmhands/978d7d2416379d6abcc38a764cd96948 

Any ideas what could be the issue ?

**Comment by cmmarslender** [comment]
Take a look at our systemd template in ansible roles - you need to set CHIA_ROOT in the systemd config file for it to apply when running via systemd.

https://github.com/Chia-Network/ansible-roles/blob/main/chia-exporter/templates/chia-exporter.service.j2#L6
